version: "3.8"
services:
  app: 
    build: 
      context: .
    volumes:
     - .:/UITP-PetFriend-Frontend-dev_sase
    ports:
    - 3000:3000
    image: app:react
    container_name: proekt_react_container
    command: npm start